services:
  # --- Infraestrutura: Banco de Dados (PostgreSQL) ---
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      # Definições iniciais do banco (usuário/senha/nome)
      - POSTGRES_DB=AgrosolutionsSensors
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - agrosolutions-network

  # --- Serviço 1: Worker Host (Consumidor) ---
  # Roda o ENTRYPOINT padrão do Dockerfile: "dotnet host/AgrosolutionsWorkerSensors.Host.dll"
  worker-host:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker-host
    environment:
      # Lógica do AppSettings: ConnectionStrings:Postgres -> ConnectionStrings__Postgres
      # Host=postgres (nome do serviço acima)
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=AgrosolutionsSensors;Username=postgres;Password=adminpassword
      
      # 2. Configurações AWS (Mapeamento do appsettings "AWS")
      - AWS__Region=sa-east-1
      - AWS__SqsQueueUrl=https://sqs.sa-east-1.amazonaws.com/405114419969/agrosolutions-identity-events
      
      # 3. Credenciais AWS (Lê do seu ambiente local ou arquivo .env)
      - AWS_ACCESS_KEY_ID=...
      - AWS_SECRET_ACCESS_KEY=...

    depends_on:
      postgres:
        condition: service_healthy

    networks:
    - agrosolutions-network

  # --- Serviço 2: Worker Generator (Produtor) ---
  # SOBRESCREVE o ENTRYPOINT para rodar o Gerador: "dotnet generator/AgrosolutionsWorkerSensors.Generator.dll"
  worker-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker-generator
    entrypoint: ["dotnet", "generator/AgrosolutionsWorkerSensors.Generator.dll"]
    environment:
     
      # IMPORTANTE: Trocamos 'localhost' pelo nome do serviço da API definido no docker-compose.
      # A porta deve ser a mesma configurada no ASPNETCORE_URLS da API (5198).
      - ApiRawUrl=http://ingestion-api:5198

      # 1. Connection String (ConnectionStrings:DefaultConnection)
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=AgrosolutionsSensors;Username=postgres;Password=adminpassword

      # 2. Configurações de Geração (GenerationSettings:IntervalSeconds)
      - GenerationSettings__IntervalSeconds=10
    networks:
      - agrosolutions-network
# Persistência de dados do banco
volumes:
  postgres_data:

networks:
  agrosolutions-network:
    external: true