// <auto-generated />
using System;
using AgrosolutionsWorkerSensors.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgrosolutionsWorkerSensors.Infrastructure.Migrations
{
    [DbContext(typeof(SensorContext))]
    [Migration("20260201010753_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgrosolutionsWorkerSensors.Domain.Entities.SensorRaw", b =>
                {
                    b.Property<Guid>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<bool>("StatusSensor")
                        .HasColumnType("boolean");

                    b.Property<string>("TypeOperation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeSensor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SensorId");

                    b.ToTable("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
