apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-common-config
  namespace: agrosolutions
data:
  DOTNET_ENVIRONMENT: "Development"
  ConnectionStrings__DefaultConnection: "Host=postgres-db;Port=5432;Database=agrosolutions_raw;Username=postgres;Password=root"
  AWS__Region: "sa-east-1"
  AWS__SqsQueueUrl: "https://sqs.sa-east-1.amazonaws.com/316295889438/agrosolutions-identity-events"

  ApiRawUrl: "http://service-ingestion"