---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workers-common-config
  namespace: agrosolutions-workers
data:
  DOTNET_ENVIRONMENT: "Production"
  ConnectionStrings__DefaultConnection: "Host=postgres-db;Port=5432;Database=agrosolutions_raw;Username=postgres;Password=root"
  AWS__Region: "sa-east-1"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft: "Warning"
  # OpenTelemetry
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-service.agrosolutions-observability:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_SERVICE_NAME: "agrosolutions-workers"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=production,service.version=1.0.0"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-host-config
  namespace: agrosolutions-workers
data:
  AWS__SqsQueueUrl: "https://sqs.sa-east-1.amazonaws.com/316295889438/agrosolutions-property-events-queue"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-generator-config
  namespace: agrosolutions-workers
data:
  ApiRawUrl: "http://ingestion-api-service.agrosolutions-ingestion.svc.cluster.local"
  GenerationSettings__IntervalSeconds: "10"
