---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-host
  namespace: agrosolutions-workers
  labels:
    app: worker-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-host
  template:
    metadata:
      labels:
        app: worker-host
    spec:
      serviceAccountName: agrosolutions-workers-sa
      initContainers:
      - name: wait-for-postgres
        image: postgres:16-alpine
        command: ["/bin/sh", "-c", "until pg_isready -h postgres-db -p 5432 -U postgres; do sleep 2; done"]
      containers:
      - name: worker-host
        image: 316295889438.dkr.ecr.sa-east-1.amazonaws.com/agrosolutions-worker:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: workers-common-config
        - configMapRef:
            name: worker-host-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-generator
  namespace: agrosolutions-workers
  labels:
    app: worker-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-generator
  template:
    metadata:
      labels:
        app: worker-generator
    spec:
      serviceAccountName: agrosolutions-workers-sa
      containers:
      - name: worker-generator
        image: 316295889438.dkr.ecr.sa-east-1.amazonaws.com/agrosolutions-worker:latest
        imagePullPolicy: Always
        command: ["dotnet", "generator/AgrosolutionsWorkerSensors.Generator.dll"]
        envFrom:
        - configMapRef:
            name: workers-common-config
        - configMapRef:
            name: worker-generator-config
